# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: cep_pgdb
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./cep_pgdb_data:/var/lib/postgresql/data
    networks:
      - back-tier

  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8088:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
     - back-tier

  wiremock:
    image: "docker.io/wiremock/wiremock:latest"
    container_name: "wiremock_cepapi"
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock_data/extensions:/var/wiremock/extensions
      - ./wiremock_data/__files:/home/wiremock/__files
      - ./wiremock_data/mappings:/home/wiremock/mappings
    networks:
      - back-tier

networks:
  back-tier: